const drawComment = require('./index');

drawComment(
  'This is my text with quite words. Here it will be. 25W WWWWWWWWWWWWWWWWWWWWWWWWW 26W WWWWWWWWWWWWWWWWWWWWWWWWWW 50W WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW 25W WWWWWWWWWWWWWWWWWWWWWWWWW next line will be with new rules 64W WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW %64 shoul be at next line 65W WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW --- 090909 lalala. Bye!',
  (err, filename) => console.log(err || filename)
);
